/* Generated automatically */
static int is_private(Param pm);
static int bin_private(char*nam,char**args,LinkList assigns,Options ops,int func);
static char*pps_getfn(Param pm);
static void pps_setfn(Param pm,char*x);
static void pps_unsetfn(Param pm,int explicit);
static zlong ppi_getfn(Param pm);
static void ppi_setfn(Param pm,zlong x);
static void ppi_unsetfn(Param pm,int explicit);
static double ppf_getfn(Param pm);
static void ppf_setfn(Param pm,double x);
static void ppf_unsetfn(Param pm,int explicit);
static char**ppa_getfn(Param pm);
static void ppa_setfn(Param pm,char**x);
static void ppa_unsetfn(Param pm,int explicit);
static HashTable pph_getfn(Param pm);
static void pph_setfn(Param pm,HashTable x);
static void pph_unsetfn(Param pm,int explicit);
static int private_wraplevel;
static int wrap_private(Eprog prog,FuncWrap w,char*name);
static HashNode getprivatenode(HashTable ht,const char*nam);
static HashNode getprivatenode2(HashTable ht,const char*nam);
static void printprivatenode(HashNode hn,int printflags);
