/* Generated automatically */
static char*paramtypestr(Param pm,int append);
static HashNode getpmparameter(UNUSED(HashTable ht),const char*name);
static void scanpmparameters(UNUSED(HashTable ht),ScanFunc func,int flags);
static void setpmcommand(Param pm,char*value);
static void unsetpmcommand(Param pm,UNUSED(int exp));
static void setpmcommands(Param pm,HashTable ht);
static HashNode getpmcommand(UNUSED(HashTable ht),const char*name);
static void scanpmcommands(UNUSED(HashTable ht),ScanFunc func,int flags);
static void setfunction(char*name,char*val,int dis);
static void setpmfunction(Param pm,char*value);
static void setpmdisfunction(Param pm,char*value);
static void unsetpmfunction(Param pm,UNUSED(int exp));
static void setfunctions(Param pm,HashTable ht,int dis);
static void setpmfunctions(Param pm,HashTable ht);
static void setpmdisfunctions(Param pm,HashTable ht);
static HashNode getfunction(UNUSED(HashTable ht),const char*name,int dis);
static HashNode getpmfunction(HashTable ht,const char*name);
static HashNode getpmdisfunction(HashTable ht,const char*name);
static void scanfunctions(UNUSED(HashTable ht),ScanFunc func,int flags,int dis);
static void scanpmfunctions(HashTable ht,ScanFunc func,int flags);
static void scanpmdisfunctions(HashTable ht,ScanFunc func,int flags);
static HashNode getfunction_source(UNUSED(HashTable ht),const char*name,int dis);
static void scanfunctions_source(UNUSED(HashTable ht),ScanFunc func,int flags,int dis);
static HashNode getpmfunction_source(HashTable ht,const char*name);
static HashNode getpmdisfunction_source(HashTable ht,const char*name);
static void scanpmfunction_source(HashTable ht,ScanFunc func,int flags);
static void scanpmdisfunction_source(HashTable ht,ScanFunc func,int flags);
static char**funcstackgetfn(UNUSED(Param pm));
static char**functracegetfn(UNUSED(Param pm));
static char**funcsourcetracegetfn(UNUSED(Param pm));
static char**funcfiletracegetfn(UNUSED(Param pm));
static HashNode getbuiltin(UNUSED(HashTable ht),const char*name,int dis);
static HashNode getpmbuiltin(HashTable ht,const char*name);
static HashNode getpmdisbuiltin(HashTable ht,const char*name);
static void scanbuiltins(UNUSED(HashTable ht),ScanFunc func,int flags,int dis);
static void scanpmbuiltins(HashTable ht,ScanFunc func,int flags);
static void scanpmdisbuiltins(HashTable ht,ScanFunc func,int flags);
static char**getreswords(int dis);
static char**reswordsgetfn(UNUSED(Param pm));
static char**disreswordsgetfn(UNUSED(Param pm));
static char**getpatchars(int dis);
static void setpmoption(Param pm,char*value);
static void unsetpmoption(Param pm,UNUSED(int exp));
static void setpmoptions(Param pm,HashTable ht);
static HashNode getpmoption(UNUSED(HashTable ht),const char*name);
static void scanpmoptions(UNUSED(HashTable ht),ScanFunc func,int flags);
static HashNode getpmmodule(UNUSED(HashTable ht),const char*name);
static void scanpmmodules(UNUSED(HashTable ht),ScanFunc func,int flags);
static void dirssetfn(UNUSED(Param pm),char**x);
static char**dirsgetfn(UNUSED(Param pm));
static HashNode getpmhistory(UNUSED(HashTable ht),const char*name);
static void scanpmhistory(UNUSED(HashTable ht),ScanFunc func,int flags);
static char**histwgetfn(UNUSED(Param pm));
static char*pmjobtext(Job jtab,int job);
static HashNode getpmjobtext(UNUSED(HashTable ht),const char*name);
static void scanpmjobtexts(UNUSED(HashTable ht),ScanFunc func,int flags);
static char*pmjobstate(Job jtab,int job);
static HashNode getpmjobstate(UNUSED(HashTable ht),const char*name);
static void scanpmjobstates(UNUSED(HashTable ht),ScanFunc func,int flags);
static char*pmjobdir(Job jtab,int job);
static HashNode getpmjobdir(UNUSED(HashTable ht),const char*name);
static void scanpmjobdirs(UNUSED(HashTable ht),ScanFunc func,int flags);
static void setpmnameddir(Param pm,char*value);
static void unsetpmnameddir(Param pm,UNUSED(int exp));
static void setpmnameddirs(Param pm,HashTable ht);
static HashNode getpmnameddir(UNUSED(HashTable ht),const char*name);
static void scanpmnameddirs(UNUSED(HashTable ht),ScanFunc func,int flags);
static HashNode getpmuserdir(UNUSED(HashTable ht),const char*name);
static void scanpmuserdirs(UNUSED(HashTable ht),ScanFunc func,int flags);
static void setalias(HashTable ht,Param pm,char*value,int flags);
static void setpmralias(Param pm,char*value);
static void setpmdisralias(Param pm,char*value);
static void setpmgalias(Param pm,char*value);
static void setpmdisgalias(Param pm,char*value);
static void setpmsalias(Param pm,char*value);
static void setpmdissalias(Param pm,char*value);
static void unsetpmalias(Param pm,UNUSED(int exp));
static void unsetpmsalias(Param pm,UNUSED(int exp));
static void setaliases(HashTable alht,Param pm,HashTable ht,int flags);
static void setpmraliases(Param pm,HashTable ht);
static void setpmdisraliases(Param pm,HashTable ht);
static void setpmgaliases(Param pm,HashTable ht);
static void setpmdisgaliases(Param pm,HashTable ht);
static void setpmsaliases(Param pm,HashTable ht);
static void setpmdissaliases(Param pm,HashTable ht);
static void assignaliasdefs(Param pm,int flags);
static HashNode getalias(HashTable alht,UNUSED(HashTable ht),const char*name,int flags);
static HashNode getpmralias(HashTable ht,const char*name);
static HashNode getpmdisralias(HashTable ht,const char*name);
static HashNode getpmgalias(HashTable ht,const char*name);
static HashNode getpmdisgalias(HashTable ht,const char*name);
static HashNode getpmsalias(HashTable ht,const char*name);
static HashNode getpmdissalias(HashTable ht,const char*name);
static void scanaliases(HashTable alht,UNUSED(HashTable ht),ScanFunc func,int pmflags,int alflags);
static void scanpmraliases(HashTable ht,ScanFunc func,int flags);
static void scanpmdisraliases(HashTable ht,ScanFunc func,int flags);
static void scanpmgaliases(HashTable ht,ScanFunc func,int flags);
static void scanpmdisgaliases(HashTable ht,ScanFunc func,int flags);
static void scanpmsaliases(HashTable ht,ScanFunc func,int flags);
static void scanpmdissaliases(HashTable ht,ScanFunc func,int flags);
static Groupset get_all_groups(void);
static HashNode getpmusergroups(UNUSED(HashTable ht),const char*name);
static void scanpmusergroups(UNUSED(HashTable ht),ScanFunc func,int flags);
