/* Generated automatically */
static void zfhandler(int sig);
static void zfalarm(int tmout);
static void zfpipe(void);
static void zfunalarm(void);
static void zfunpipe(void);
static int zfmovefd(int fd);
static void zfsetparam(char*name,void*val,int flags);
static void zfunsetparam(char*name);
static char*zfargstring(char*cmd,char**args);
static int zfgetline(char*ln,int lnsize,int tmout);
static int zfgetmsg(void);
static int zfsendcmd(char*cmd);
static int zfopendata(char*name,union tcp_sockaddr*zdsockp,int*is_passivep);
static void zfclosedata(void);
static int zfgetdata(char*name,char*rest,char*cmd,int getsize);
static int zfstats(char*fnam,int remote,off_t*retsize,char**retmdtm,int fd);
static void zfstarttrans(char*nam,int recv,off_t sz);
static void zfendtrans(void);
static int zfread(int fd,char*bf,off_t sz,int tmout);
static int zfwrite(int fd,char*bf,off_t sz,int tmout);
static int zfread_block(int fd,char*bf,off_t sz,int tmout);
static int zfwrite_block(int fd,char*bf,off_t sz,int tmout);
static int zfsenddata(char*name,int recv,int progress,off_t startat);
static int zftp_open(char*name,char**args,int flags);
static char*zfgetinfo(char*prompt,int noecho);
static int zftp_params(UNUSED(char*name),char**args,UNUSED(int flags));
static int zftp_login(char*name,char**args,UNUSED(int flags));
static int zftp_test(UNUSED(char*name),UNUSED(char**args),UNUSED(int flags));
static int zftp_dir(char*name,char**args,int flags);
static int zftp_cd(UNUSED(char*name),char**args,int flags);
static int zfgetcwd(void);
static int zfsettype(int type);
static int zftp_type(char*name,char**args,int flags);
static int zftp_mode(char*name,char**args,UNUSED(int flags));
static int zftp_local(UNUSED(char*name),char**args,int flags);
static int zftp_getput(char*name,char**args,int flags);
static int zftp_delete(UNUSED(char*name),char**args,UNUSED(int flags));
static int zftp_mkdir(UNUSED(char*name),char**args,int flags);
static int zftp_rename(UNUSED(char*name),char**args,UNUSED(int flags));
static int zftp_quote(UNUSED(char*name),char**args,int flags);
static void zfclose(int leaveparams);
static int zftp_close(UNUSED(char*name),UNUSED(char**args),UNUSED(int flags));
static void newsession(char*nm);
static void switchsession(char*nm);
static void freesession(Zftp_session sptr);
static int zftp_session(UNUSED(char*name),char**args,UNUSED(int flags));
static int zftp_rmsession(UNUSED(char*name),char**args,UNUSED(int flags));
static int bin_zftp(char*name,char**args,UNUSED(Options ops),UNUSED(int func));
