/* Generated automatically */
static __thread Cmlist cmatcher;
static void createcompctltable(void);
static void freecompctlp(HashNode hn);
static void freecompctl(Compctl cc);
static void freecompcond(void*a);
static int compctlread(char*name,char**args,Options ops,char*reply);
static Cmlist cpcmlist(Cmlist l);
static int set_gmatcher(char*name,char**argv);
static int get_gmatcher(char*name,char**argv);
static void print_gmatcher(int ac);
static int get_compctl(char*name,char***av,Compctl cc,int first,int isdef,int cl);
static int get_xcompctl(char*name,char***av,Compctl cc,int isdef);
static int cc_assign(char*name,Compctl*ccptr,Compctl cct,int reass);
static void cc_reassign(Compctl cc);
static void compctl_process_cc(char**s,Compctl cc);
static void printcompctl(char*s,Compctl cc,int printflags,int ispat);
static void printcompctlp(HashNode hn,int printflags);
static int bin_compctl(char*name,char**argv,UNUSED(Options ops),UNUSED(int func));
static void addmatch(char*s,char*t);
static void maketildelist(void);
static int getcpat(char*str,int cpatindex,char*cpat,int class);
static void dumphashtable(HashTable ht,int what);
static void addhnmatch(HashNode hn,UNUSED(int flags));
static char*getreal(char*str);
static void gen_matches_files(int dirs,int execs,int all);
static int makecomplistctl(int flags);
static int makecomplistglobal(char*os,int incmd,UNUSED(int lst),int flags);
static int makecomplistcmd(char*os,int incmd,int flags);
static int makecomplistpc(char*os,int incmd);
static void makecomplistcc(Compctl cc,char*s,int incmd);
static void makecomplistor(Compctl cc,char*s,int incmd,int compadd,int sub);
static void makecomplistlist(Compctl cc,char*s,int incmd,int compadd);
static void makecomplistext(Compctl occ,char*os,int incmd);
static int sep_comp_string(char*ss,char*s,int noffs);
static void makecomplistflags(Compctl cc,char*s,int incmd,int compadd);
