/* Generated automatically */
static void zleunsetfn(Param pm,int exp);
static void set_buffer(UNUSED(Param pm),char*x);
static char*get_buffer(UNUSED(Param pm));
static void set_cursor(UNUSED(Param pm),zlong x);
static zlong get_cursor(UNUSED(Param pm));
static void set_mark(UNUSED(Param pm),zlong x);
static zlong get_mark(UNUSED(Param pm));
static void set_region_active(UNUSED(Param pm),zlong x);
static zlong get_region_active(UNUSED(Param pm));
static void set_lbuffer(UNUSED(Param pm),char*x);
static char*get_lbuffer(UNUSED(Param pm));
static void set_rbuffer(UNUSED(Param pm),char*x);
static char*get_rbuffer(UNUSED(Param pm));
static char*get_prebuffer(UNUSED(Param pm));
static char*get_widget(UNUSED(Param pm));
static char*get_widgetfunc(UNUSED(Param pm));
static char*get_widgetstyle(UNUSED(Param pm));
static char*get_lwidget(UNUSED(Param pm));
static char*get_keymap(UNUSED(Param pm));
static char*get_keys(UNUSED(Param pm));
static zlong get_keys_queued_count(UNUSED(Param pm));
static void set_numeric(UNUSED(Param pm),zlong x);
static zlong get_numeric(UNUSED(Param pm));
static void unset_numeric(Param pm,int exp);
static void set_histno(UNUSED(Param pm),zlong x);
static zlong get_histno(UNUSED(Param pm));
static zlong get_bufferlines(UNUSED(Param pm));
static zlong get_pending(UNUSED(Param pm));
static zlong get_recursive(UNUSED(Param pm));
static zlong get_yankstart(UNUSED(Param pm));
static zlong get_yankend(UNUSED(Param pm));
static zlong get_yankactive(UNUSED(Param pm));
static void set_yankstart(UNUSED(Param pm),zlong i);
static void set_yankend(UNUSED(Param pm),zlong i);
static zlong get_isearchmatchstart(UNUSED(Param pm));
static zlong get_isearchmatchend(UNUSED(Param pm));
static zlong get_isearchmatchactive(UNUSED(Param pm));
static zlong get_suffixstart(UNUSED(Param pm));
static zlong get_suffixend(UNUSED(Param pm));
static zlong get_suffixactive(UNUSED(Param pm));
static char*get_cutbuffer(UNUSED(Param pm));
static void set_cutbuffer(UNUSED(Param pm),char*x);
static void unset_cutbuffer(Param pm,int exp);
static void set_killring(UNUSED(Param pm),char**x);
static char**get_killring(UNUSED(Param pm));
static void unset_killring(Param pm,int exp);
static void set_register(Param pm,char*value);
static void set_register_buf(Param pm,char*value);
static void unset_register(Param pm,UNUSED(int exp));
static void scan_registers(UNUSED(HashTable ht),ScanFunc func,int flags);
static HashNode get_registers(UNUSED(HashTable ht),const char*name);
static void set_registers(Param pm,HashTable ht);
static void unset_registers(Param pm,int exp);
static void set_predisplay(UNUSED(Param pm),char*x);
static char*get_predisplay(UNUSED(Param pm));
static void set_postdisplay(UNUSED(Param pm),char*x);
static char*get_postdisplay(UNUSED(Param pm));
static char*get_lasearch(UNUSED(Param pm));
static char*get_lsearch(UNUSED(Param pm));
static char*get_context(UNUSED(Param pm));
static char*get_zle_state(UNUSED(Param pm));
